---
name: "Build"

on:
  workflow_dispatch:
    inputs:
      rust_version:
        type: "string"
        description: "Rust version"
        required: true
        default: "1.83.0"

      coreos_installer_version:
        type: "string"
        description: "CoreOS Installer version"
        required: true
        default: "0.23.0"

jobs:
  build:
    name: "Build"
    strategy:
      matrix:
        target:
          - os: "x86_64-linux"
            labels: "ubuntu-latest"
          - os: "aarch64-linux"
            labels: "aarch64-k8s-arc"
    runs-on: "${{ matrix.target.labels }}"
    steps:
      - name: "Download & prepare sources"
        run: |
          set -euo pipefail

          mkdir -p coreos-installer vendor

          curl -Lfs -o crate.tar.gz https://github.com/coreos/coreos-installer/archive/refs/tags/v${{ inputs.coreos_installer_version }}.tar.gz
          curl -Lfs -o vendor.tar.gz https://github.com/coreos/coreos-installer/releases/download/v${{ inputs.coreos_installer_version }}/coreos-installer-${{ inputs.coreos_installer_version }}-vendor.tar.gz

          sha256sum crate.tar.gz vendor.tar.gz

          tar -C coreos-installer --strip-components=1 -xzf crate.tar.gz
          tar -C vendor --transform 's|^\./vendor/||' --transform 's|^vendor/||' -xzf vendor.tar.gz

          # Set up Cargo config
          install -D -m 644 /dev/stdin coreos-installer/.cargo/config.toml <<EOF
          [source.crates-io]
          replace-with = "vendored-sources"

          [source.vendored-sources]
          directory = "/work/vendor"
          EOF

      - name: "Build coreos-installer"
        uses: "addnab/docker-run-action@v3"
        with:
          image: "rust:${{ inputs.rust_version }}-alpine"
          options: |
            -v ${{ github.workspace }}:/work
          run: |
            set -e -x

            apk add --no-cache musl-dev openssl-dev openssl-libs-static pkgconf zstd-dev zstd-static

            cd /work/coreos-installer
            cargo build --frozen --locked --offline --release

            test -f target/release/coreos-installer
            mkdir -p /work/output
            cp -v target/release/coreos-installer "/work/output/coreos-installer-${{ matrix.target.os }}"

      - name: "Upload artifact"
        uses: "actions/upload-artifact@v4"
        with:
          name: "coreos-installer-${{ matrix.target.os }}"
          path: "output/coreos-installer-${{ matrix.target.os }}"
          retention-days: 1

  publish:
    name: "Publish"
    needs: "build"
    runs-on: "ubuntu-latest"
    if: "${{ github.event_name == 'workflow_dispatch' }}"
    permissions:
      attestations: "write"
      contents: "write"
      id-token: "write"
    steps:
      - id: "checkout"
        name: "Check out sources"
        uses: "actions/checkout@v4"

      - id: "setup-deno"
        name: "Setup Deno"
        uses: "denoland/setup-deno@v1"
        with:
          deno-version: "1.42.4"

      - id: "download-artifact"
        name: "Download binary from workspace"
        uses: "actions/download-artifact@v4"
        with:
          pattern: "coreos-installer-*"
          path: "artifacts"
          merge-multiple: true

      - id: "generate-metadata"
        name: "Generate build metadata"
        run: |
          set -euo pipefail

          mkdir -p metadata

          (cd artifacts && sha256sum *) | grep -F -v ".gz" >> metadata/SHA256SUMS
          # Produce { name, os, sha256 } from every SHA256SUMS line
          jq -ecr -s -R '[split("\n")[] | select(. | length > 0) | split("\\s+";"") | { name: .[1], os: (.[1] | sub("coreos-installer-"; ""; "")), sha256: .[0] }]' < metadata/SHA256SUMS \
            | jq --arg version "${{ inputs.coreos_installer_version }}" '{ version: $version, assets: . }' > metadata/assets.json

          gzip -k artifacts/coreos-installer*
          (cd artifacts && sha256sum *.gz) >> metadata/SHA256SUMS

      - id: "generate-install-script"
        name: "Generate install script"
        run: |
          set -euo pipefail

          mkdir -p scripts
          ./hack/gen_installer.ts metadata/assets.json

          (cd scripts && sha256sum *) >> metadata/SHA256SUMS

      - id: "publish"
        name: "Publish Github release"
        uses: "softprops/action-gh-release@v2"
        with:
          body: |
            For changes, see here: https://github.com/coreos/coreos-installer/releases/tag/v${{ inputs.coreos_installer_version }}
          files: |
            artifacts/coreos-installer*
            scripts/installer.sh
            metadata/assets.json
            metadata/SHA256SUMS
          tag_name: "${{ inputs.coreos_installer_version }}"
          draft: false
          prerelease: false
          fail_on_unmatched_files: true
          generate_release_notes: false

      - id: "attest"
        name: "Attest"
        uses: "actions/attest-build-provenance@v1"
        with:
          subject-path: |
            artifacts/coreos-installer*
            scripts/installer.sh
            metadata/assets.json
            metadata/SHA256SUMS
